// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJjtrKDxQ6oNHdx_1GWnIsjCqiJXj-o8',
    appId: '1:86816765600:web:6106a804dfba2dcf32fbc5',
    messagingSenderId: '86816765600',
    projectId: 'resto-app-acf63',
    authDomain: 'resto-app-acf63.firebaseapp.com',
    storageBucket: 'resto-app-acf63.appspot.com',
    measurementId: 'G-RM7BSEE1S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7sqKLIEvDu3OQpATtgEmJzcgQl_iDdk8',
    appId: '1:86816765600:android:16c4e952c910f5d632fbc5',
    messagingSenderId: '86816765600',
    projectId: 'resto-app-acf63',
    storageBucket: 'resto-app-acf63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvsM7KFyE2tITfvMlKRk-UYm0XnfC5NEg',
    appId: '1:86816765600:ios:ff9f02969c32a30b32fbc5',
    messagingSenderId: '86816765600',
    projectId: 'resto-app-acf63',
    storageBucket: 'resto-app-acf63.appspot.com',
    iosBundleId: 'com.example.uasppb2021130007',
  );
}
